name: Build Installer

on:
  workflow_run:
    workflows: ["Lint & Check"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Get short SHA
      run: |
        $sha = git rev-parse --short HEAD
        echo "SHORT_SHA=$sha" >> $env:GITHUB_ENV
        echo $sha > frontend/version.txt
        echo $sha > backend/version.txt
        echo "RELEASE_BUILD=true" >> $env:GITHUB_ENV

    - name: Set branch suffix and prerelease flag
      run: |
        if ("$env:GITHUB_REF_NAME" -eq "main") {
          echo "BRANCH_SUFFIX=_main" >> $env:GITHUB_ENV
          echo "IS_PRERELEASE=false" >> $env:GITHUB_ENV
        } else {
          echo "BRANCH_SUFFIX=_dev" >> $env:GITHUB_ENV
          echo "IS_PRERELEASE=true" >> $env:GITHUB_ENV
        }

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXEs
      run: .\build_windows.bat

    - name: Install Inno Setup
      run: choco install innosetup -y

    - name: Build Installer
      run: |
        mkdir C:\installer_output
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" /Qp /O"C:\installer_output" /F"kav1_setup_${{ env.SHORT_SHA }}" kav1.iss

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: installer
        path: C:/installer_output/kav1_setup_${{ env.SHORT_SHA }}.exe
