name: Lint & Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install tools
      run: |
        pip install flake8 black mypy

    - name: Run flake8
      run: flake8 .

    - name: Run black check
      run: black --check .

    - name: Run mypy
      run: mypy .
