name: Create Release

on:
  workflow_run:
    workflows: ["Build Installer"]
    types: [completed]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/download-artifact@v4
      with:
        name: installer
        path: ./output

    - run: |
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        if [[ "$GITHUB_REF_NAME" == "main" ]]; then
          echo "BRANCH_SUFFIX=_main" >> $GITHUB_ENV
          echo "IS_PRERELEASE=false" >> $GITHUB_ENV
        else
          echo "BRANCH_SUFFIX=_dev" >> $GITHUB_ENV
          echo "IS_PRERELEASE=true" >> $GITHUB_ENV
        fi

    - run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git tag -a "${{ env.SHORT_SHA }}" -m "${{ env.SHORT_SHA }}"
        git push origin "${{ env.SHORT_SHA }}"

    - id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.SHORT_SHA }}
        release_name: ${{ env.BRANCH_SUFFIX }} Build ${{ env.SHORT_SHA }}
        draft: false
        prerelease: ${{ env.IS_PRERELEASE }}

    - uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/kav1_setup_${{ env.SHORT_SHA }}.exe
        asset_name: kav1_setup_${{ env.SHORT_SHA }}.exe
        asset_content_type: application/octet-stream
